// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTeapotsWebProject.Data.DBContexts;

#nullable disable

namespace SmartTeapotsWebProject.Migrations
{
    [DbContext(typeof(SmartTeapotsDbContext))]
    [Migration("20220627155459_AddUserAndOrderTables")]
    partial class AddUserAndOrderTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SmartTeapotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SmartTeapotId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SmartTeapotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SmartTeapotId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.SmartTeapot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProducingCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SmartTeapots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2.2999999999999998,
                            Color = "Black",
                            Material = "Plastic",
                            Name = "SmartTeapot1",
                            Power = 1200,
                            Price = 2399.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_1.png",
                            Quantity = 12,
                            Warranty = 12
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1.3999999999999999,
                            Color = "Brown",
                            Material = "Metal",
                            Name = "SmartTeapot2",
                            Power = 1400,
                            Price = 1289.0,
                            Producer = "Tefal",
                            ProducingCountry = "Germany",
                            ProductImg = "/img/catalog/catalog_2.png",
                            Quantity = 23,
                            Warranty = 24
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot3",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_3.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot4",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_4.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot5",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_5.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot6",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_6.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot7",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_7.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot8",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_8.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot9",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_9.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot10",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_10.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot11",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_11.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot12",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_12.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot13",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_13.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot14",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_14.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot15",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_15.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot16",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_16.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot17",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_17.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot18",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_18.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot19",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_19.png",
                            Quantity = 4,
                            Warranty = 18
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 1.7,
                            Color = "White",
                            Material = "Plastic",
                            Name = "SmartTeapot20",
                            Power = 1500,
                            Price = 3259.0,
                            Producer = "Xiaomi",
                            ProducingCountry = "China",
                            ProductImg = "/img/catalog/catalog_20.png",
                            Quantity = 4,
                            Warranty = 18
                        });
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.CartItem", b =>
                {
                    b.HasOne("SmartTeapotsWebProject.Data.Models.SmartTeapot", "SmartTeapot")
                        .WithMany()
                        .HasForeignKey("SmartTeapotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartTeapot");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.Order", b =>
                {
                    b.HasOne("SmartTeapotsWebProject.Data.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTeapotsWebProject.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("SmartTeapotsWebProject.Data.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTeapotsWebProject.Data.Models.SmartTeapot", "SmartTeapot")
                        .WithMany()
                        .HasForeignKey("SmartTeapotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("SmartTeapot");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.User", b =>
                {
                    b.HasOne("SmartTeapotsWebProject.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("SmartTeapotsWebProject.Data.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
